#!/usr/bin/env python3
"""Generate sapi/tables.asm: data of the port derived from the original.

- cga_screen: the start screen as CGA-1V data (EGA mode: 4 pixels + 4-bit colour code a byte),
  made from the Spectrum screen at the start of the music (tools/zx_start_screen.bin, from
  tools/zx/capture_screen.py): rows 0-22 in the middle of the CGA, the line animation (rows
  0-15) with code ANIM_CODE, others BRIGHT * 8 + INK of their attribute (the paper is black).
  Row 23 (scroller) stays empty. RLE: n = 01h-7Fh: n literal bytes follow; n = 80h-FFh: the
  next byte n - 7Eh times; 00h = end;
- anim_lines: CGA address of each line of the animation (Spectrum lines 0-127);
- vu_cga_rows: CGA addresses of the 15 rows of the VU meters (Spectrum vu_rows FF06h);
- rgb_table: the 16 Spectrum colours (BRIGHT * 8 + ink) as R, G, B for the Bt476 (6 bits);
- fnum_table: YM3812 F-number of the normalised AY period N = 2283-4564 in steps of 4.
"""
import os

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
SCREEN = os.path.join(ROOT, 'tools', 'zx_start_screen.bin')
OUT = os.path.join(ROOT, 'sapi', 'tables.asm')

CGA = 0xC000
CGA_TOP = 4         # Spectrum line 0 = CGA line 4
CGA_LEFT = 8        # Spectrum column 0 = CGA byte 8 (32 pixels)
ANIM_CODE = 8
NORMAL, BRIGHT = 52, 63     # 6-bit levels of a normal and a bright colour
# vu_rows of the original (FF06h): Spectrum screen addresses of the rows of the bars
VU_ROWS = [0x56BA, 0x54BA, 0x52BA, 0x50BA, 0x569A, 0x549A, 0x529A, 0x509A,
           0x567A, 0x547A, 0x527A, 0x507A, 0x565A, 0x545A, 0x525A]
# YM3812: F-number = K / N, K = 110840 * 2^20 / 49716 (the tone of an AY period P is
# 110837.5 / P Hz, the same constant as the MZ-800 PSG of SAPI-Flappy)
YM_K = 0x23ABEC
FNUM_LO, FNUM_HI, FNUM_STEP = 2283, 4564, 4


def zx_addr(row, line, col):
    return 0x4000 + ((row & 0x18) << 8) + (line << 8) + ((row & 7) << 5) + col


def cga_addr(ly, byte):
    return CGA + (ly + CGA_TOP) * 80 + CGA_LEFT + byte


def cga_screen(scr):
    img = bytearray(16000)
    for ly in range(184):                   # rows 0-22
        row, line = ly >> 3, ly & 7
        for col in range(32):
            b = scr[zx_addr(row, line, col) - 0x4000]
            attr = scr[6144 + row * 32 + col]
            code = ANIM_CODE if row < 16 else (attr & 7) | (8 if attr & 0x40 else 0)
            for k, nib in enumerate((b & 0xF0, (b << 4) & 0xF0)):
                v = nib | code if (row < 16 or nib) else 0
                img[(ly + CGA_TOP) * 80 + CGA_LEFT + 2 * col + k] = v
    return img


def rle(data):
    out, i = [], 0
    while i < len(data):
        n = 1
        while i + n < len(data) and data[i + n] == data[i] and n < 129:
            n += 1
        if n >= 3:
            out += [0x7E + n, data[i]]
            i += n
            continue
        j = i                               # literals up to the next run of 3
        while j < len(data) and j - i < 127:
            if j + 2 < len(data) and data[j] == data[j + 1] == data[j + 2]:
                break
            j += 1
        out += [j - i] + list(data[i:j])
        i = j
    return out + [0]


def hx(v, w=2):
    s = ('%0' + str(w) + 'X') % v
    return ('0' + s if s[0] in 'ABCDEF' else s) + 'h'


def defs(w, name, values, per, width=2):
    w.append(name + ':')
    for k in range(0, len(values), per):
        w.append('\t%s ' % ('defb' if width == 2 else 'defw') +
                 ','.join(hx(v, width) for v in values[k:k + per]))


def main():
    scr = open(SCREEN, 'rb').read()
    assert len(scr) == 6912
    data = rle(cga_screen(scr))
    w = ['; Generated by tools/make_tables.py, do not edit.', '']
    w.append('CGA_TOP:\tequ %d\t\t\t; Spectrum line 0 = CGA line %d' % (CGA_TOP, CGA_TOP))
    w.append('CGA_LEFT:\tequ %d\t\t\t; Spectrum column 0 = CGA byte %d' % (CGA_LEFT, CGA_LEFT))
    w.append('SCROLL_CGA:\tequ %s\t\t; scroller: CGA address of line 0 (row 23, column 1)'
             % hx(cga_addr(184, 2), 4))
    w.append('FNUM_LO:\tequ %d\t\t\t; fnum_table: normalised AY periods %d-%d, step %d'
             % (FNUM_LO, FNUM_LO, FNUM_HI, FNUM_STEP))
    w.append('')
    w.append('; Start screen on the CGA, RLE: %d bytes' % len(data))
    defs(w, 'cga_screen', data, 16)
    w.append('')
    w.append('; CGA address of the lines of the line animation (Spectrum lines 0-127)')
    defs(w, 'anim_lines', [cga_addr(y, 0) for y in range(128)], 8, 4)
    w.append('')
    w.append('; CGA addresses of the rows of the VU meters (vu_rows of the original), bar of channel 1')
    vu = []
    for a in VU_ROWS:
        o = a - 0x4000
        row = ((o >> 8) & 0x18) | ((o >> 5) & 7)
        vu.append(cga_addr(row * 8 + ((o >> 8) & 7), 2 * (o & 0x1F)))
    defs(w, 'vu_cga_rows', vu, 8, 4)
    w.append('')
    w.append('; Spectrum colours 0-15 (BRIGHT * 8 + colour): R, G, B for the Bt476')
    w.append('rgb_table:')
    for c in range(16):
        lv = BRIGHT if c & 8 else NORMAL
        if c == 8:
            lv = 0
        r, g, b = (lv if c & 2 else 0), (lv if c & 4 else 0), (lv if c & 1 else 0)
        w.append('\tdefb %s,%s,%s\t\t; %d' % (hx(r), hx(g), hx(b), c))
    w.append('')
    fn = []
    for n in range(FNUM_LO, FNUM_HI + 1, FNUM_STEP):
        mid = n + (FNUM_STEP - 1) / 2.0
        fn.append(min(1023, int(round(YM_K / mid))))
    w.append('; YM3812 F-number of the normalised AY period N (N = FNUM_LO + 4 * index)')
    defs(w, 'fnum_table', fn, 8, 4)
    open(OUT, 'w', newline='\n').write('\n'.join(w) + '\n')
    print('%s: start screen RLE %d bytes, fnum_table %d entries' % (OUT, len(data), len(fn)))


if __name__ == '__main__':
    main()
