#!/usr/bin/env python3
"""Generate sapi/tables.asm: data of the port derived from the original.

- start_screen: the Spectrum screen at the start of the music (build/zx_start_screen.bin, from
  tools/zx/capture_screen.py; a copy is kept in tools/zx_start_screen.bin so that the build does
  not need zx84), RLE: 00h n = n zero bytes (n = 0: 256), other bytes are literal;
- cga_lines: CGA address of each Spectrum pixel line 0-191 (CGA_TOP lines from the top,
  CGA_LEFT bytes from the left: the 256 x 192 Spectrum screen in the middle of 320 x 200);
- zx_rgb: the 16 Spectrum colours (BRIGHT * 8 + ink) as R, G, B for the Bt476 (6 bits);
- row 23 (scroller): fixed colour codes, their palette entries and r23_line (unrolled copy).
"""
import os

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
SCREEN = os.path.join(ROOT, 'tools', 'zx_start_screen.bin')
OUT = os.path.join(ROOT, 'sapi', 'tables.asm')

CGA = 0xC000
CGA_TOP = 4
CGA_LEFT = 8
NORMAL, BRIGHT = 52, 63     # 6-bit levels of a normal and a bright colour


def rle(data):
    out, i = [], 0
    while i < len(data):
        if data[i] == 0:
            n = 1
            while i + n < len(data) and data[i + n] == 0 and n < 256:
                n += 1
            out += [0, n & 0xFF]
            i += n
        else:
            out.append(data[i])
            i += 1
    return out


def hx(v, w=2):
    s = ('%0' + str(w) + 'X') % v
    return ('0' + s if s[0] in 'ABCDEF' else s) + 'h'


def main():
    scr = open(SCREEN, 'rb').read()
    assert len(scr) == 6912
    data = rle(scr)
    w = []
    w.append('; Generated by tools/make_tables.py, do not edit.')
    w.append('')
    w.append('CGA_TOP:\tequ %d\t\t\t; Spectrum line 0 = CGA line %d' % (CGA_TOP, CGA_TOP))
    w.append('CGA_LEFT:\tequ %d\t\t\t; Spectrum column 0 = CGA byte %d' % (CGA_LEFT, CGA_LEFT))
    w.append('')
    w.append('; Spectrum screen at the start of the music (BASIC 9500 done, USR 49500), RLE: %d bytes'
             % len(data))
    w.append('start_screen:')
    for k in range(0, len(data), 16):
        w.append('\tdefb ' + ','.join(hx(b) for b in data[k:k + 16]))
    w.append('')
    w.append('; CGA address of Spectrum pixel line 0-191')
    w.append('cga_lines:')
    for y in range(0, 192, 4):
        w.append('\tdefw ' + ','.join(hx(CGA + (y + k + CGA_TOP) * 80 + CGA_LEFT, 4) for k in range(4)))
    w.append('')
    w.append('; Row 23: fixed colour code of each column (platform.asm, zx_flush_frame)')
    codes = [0] + [9 + c % 7 for c in range(1, 31)] + [0]
    w.append('r23_codes:')
    w.append('\tdefb ' + ','.join(str(c) for c in codes[:16]))
    w.append('\tdefb ' + ','.join(str(c) for c in codes[16:]))
    w.append('; palette entries (band 5) of the codes of columns 24-30')
    w.append('r23_pal:')
    w.append('\tdefb ' + ','.join(str(5 * 32 + codes[c] * 2 + 1) for c in range(24, 31)))
    w.append('')
    w.append('; ---- r23_line')
    w.append('; Pixels of columns 1-30 of a line of row 23 to the CGA with the fixed codes.')
    w.append('; HL = zx_screen address of column 1, DE = CGA address of column 1.')
    w.append('r23_line:')
    for c in range(1, 31):
        k = codes[c]
        w += ['\tld a,(hl)', '\tand 0F0h', '\tor %d' % k, '\tld (de),a', '\tinc de',
              '\tld a,(hl)', '\tadd a,a', '\tadd a,a', '\tadd a,a', '\tadd a,a', '\tor %d' % k,
              '\tld (de),a']
        if c < 30:
            w += ['\tinc de', '\tinc l']
    w.append('\tret')
    w.append('')
    w.append('; Spectrum colours 0-15 (BRIGHT * 8 + colour): R, G, B for the Bt476')
    w.append('zx_rgb:')
    for c in range(16):
        lv = BRIGHT if c & 8 else NORMAL
        if c == 8:
            lv = 0
        r, g, b = (lv if c & 2 else 0), (lv if c & 4 else 0), (lv if c & 1 else 0)
        w.append('\tdefb %s,%s,%s\t\t; %d' % (hx(r), hx(g), hx(b), c))
    open(OUT, 'w', newline='\n').write('\n'.join(w) + '\n')
    print('%s: screen RLE %d bytes' % (OUT, len(data)))


if __name__ == '__main__':
    main()
